snyk/snyk-visual-studio-plugin

Snyk.Code.Library.Tests/SnykCode/BundleServiceTest.cs
Snyk.Code.Library.Tests/SnykCode/SnykCodeClientTest.cs
Snyk.Code.Library/Api/Dto/CodeFileDto.cs
Snyk.Code.Library/Api/SnykCodeClient.cs
Snyk.Code.Library/BundleService.cs

Add Upload files via REST API implementation.

[ROAD-157] Feat: add file upload rest api implementation

---

Snyk.Code.Library.Tests/Resources/HelloWorld.cs
Snyk.Code.Library.Tests/Resources/app1.js
Snyk.Code.Library.Tests/Resources/app2.js
Snyk.Code.Library.Tests/Snyk.Code.Library.Tests.csproj
Snyk.Code.Library.Tests/SnykCode/SnykCodeClientTest.cs
Snyk.Code.Library/Api/Dto/Analysis/AnalysisResultDto.cs
Snyk.Code.Library/Api/Dto/Analysis/AnalysisResultsDto.cs
Snyk.Code.Library/Api/Dto/Analysis/CoverageDto.cs
Snyk.Code.Library/Api/Dto/Analysis/ExampleCommitFixDto.cs
Snyk.Code.Library/Api/Dto/Analysis/FileDto.cs
Snyk.Code.Library/Api/Dto/Analysis/LineDto.cs
Snyk.Code.Library/Api/Dto/Analysis/MarkerDto.cs
Snyk.Code.Library/Api/Dto/Analysis/PositionDto.cs
Snyk.Code.Library/Api/Dto/Analysis/SuggestionDto.cs
Snyk.Code.Library/Api/Dto/Analysis/SuggestionIdToFileDto.cs
Snyk.Code.Library/Api/Dto/Analysis/TimingDto.cs
Snyk.Code.Library/Api/Dto/BundleResponseDto.cs
Snyk.Code.Library/Api/Dto/CodeFileDto.cs
Snyk.Code.Library/Api/Dto/CreateBundleRequestDto.cs
Snyk.Code.Library/Api/Dto/ExtendBundleRequestDto.cs
Snyk.Code.Library/Api/Dto/FiltersDto.cs
Snyk.Code.Library/Api/Dto/LoginResponseDto.cs
Snyk.Code.Library/Api/SnykCodeClient.cs
Snyk.Code.Library/Snyk.Code.Library.csproj

Add implementation for get analysis REST API and tests.

[ROAD-106] Feat: add get analysis to SnykCodeClient.

---

Snyk.Code.Library.Tests/Snyk.Code.Library.Tests.csproj
Snyk.Code.Library.Tests/SnykCode/BundleServiceTest.cs
Snyk.Code.Library/Api/Dto/BundleResponseDto.cs
Snyk.Code.Library/Api/ISnykCodeClient.cs
Snyk.Code.Library/Api/SnykCodeClient.cs
Snyk.Code.Library/BundleService.cs
Snyk.Code.Library/Snyk.Code.Library.csproj

Now all calls for SnykCodeClient in BundleService are mocked.

[ROAD-186] Feat: add mocks in BundleService for SnykCodeClient.

---

README.md

Add section how to find the logs for Visual Studio.

Feat: add section how to find the log files.

---

Snyk.Code.Library.Tests/SnykCode/BundleServiceTest.cs
Snyk.Code.Library.Tests/SnykCode/SnykCodeClientTest.cs
Snyk.Code.Library/Api/SnykCodeClient.cs
Snyk.Code.Library/Service/AnalysisService.cs
Snyk.Code.Library/Service/BundleService.cs
Snyk.Code.Library/Service/FiltersService.cs
Snyk.Code.Library/Service/SnykCodeService.cs
Snyk.Code.Library/Snyk.Code.Library.csproj
Snyk.Common/CollectionExtensions.cs
Snyk.Common/Json.cs
Snyk.Common/LogManager.cs
Snyk.Common/Properties/AssemblyInfo.cs
Snyk.Common/Sha256.cs
Snyk.Common/Snyk.Common.csproj
Snyk.Common/SnykDirectory.cs
Snyk.Common/packages.config
Snyk.VisualStudio.Extension/Snyk.VisualStudio.Extension.csproj
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/CLI/Download/SnykCliDownloader.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/CLI/SnykCli.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/SnykAnalytics/SnykAnalyticsService.cs
snyk-visual-studio-plugin.sln

Added SeriLog for extension.
Logs saved to AppData/Snyk/snyk-extension.log.
P.S.: please, note I added not so many logs following the example of how Github VS extension logging works.

[ROAD-207] Feat: add logger

---

Snyk.Code.Library.Tests/Snyk.Code.Library.Tests.csproj
Snyk.Code.Library/Snyk.Code.Library.csproj
Snyk.Code.Library/packages.config
Snyk.Common/Snyk.Common.csproj
Snyk.Common/packages.config
Snyk.VisualStudio.Extension.Tests/Snyk.VisualStudio.Extension.Tests.csproj
Snyk.VisualStudio.Extension.Tests/packages.config
Snyk.VisualStudio.Extension/Snyk.VisualStudio.Extension.csproj
Snyk.VisualStudio.Extension/packages.config

Added missing analyzers in projects.

[ROAD-184] Feat: analyzers consistency

---

Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/Service/SnykSolutionService.cs

[ROAD-277] Fix: snykcode scan freezes issue

---

Snyk.Code.Library/Domain/Analysis/Marker.cs
Snyk.Code.Library/Domain/Analysis/MarkerByPositionLineComparer.cs
Snyk.Code.Library/Domain/Analysis/Position.cs
Snyk.Code.Library/Domain/Analysis/Suggestion.cs
Snyk.Code.Library/Service/AnalysisService.cs
Snyk.Code.Library/Snyk.Code.Library.csproj
Snyk.VisualStudio.Extension/Snyk.VisualStudio.Extension.csproj
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/Service/SnykService.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/Service/VsCodeService.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/DescriptionHeaderPanel.xaml.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/DescriptionPanel.xaml
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/DescriptionPanel.xaml.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/OssDescriptionControl.xaml
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/OssDescriptionControl.xaml.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/SnykCode/DataFlowStep.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/SnykCode/DataFlowStepsControl.xaml
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/SnykCode/DataFlowStepsControl.xaml.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/SnykCode/DataFlowStepsViewModel.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/SnykCode/SnykCodeDescriptionControl.xaml
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/SnykCode/SnykCodeDescriptionControl.xaml.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/SnykToolWindowControl.xaml.cs

Add data flow grid to SnykCode description panel.

[ROAD-226] Feat: data flow grid

---

Snyk.Code.Library/Api/Dto/Analysis/SuggestionDto.cs
Snyk.Code.Library/Domain/Analysis/Suggestion.cs
Snyk.Code.Library/Service/AnalysisService.cs
Snyk.VisualStudio.Extension/Snyk.VisualStudio.Extension.csproj
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/SnykCode/DataFlowStepsControl.xaml.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/SnykCode/ExternalExampleFixesControl.xaml
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/SnykCode/ExternalExampleFixesControl.xaml.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/SnykCode/SnykCodeDescriptionControl.xaml.cs

Add external example fixes panel.

[ROAD-227] Feat: external example fixes control

---

Snyk.Code.Library/Domain/Analysis/Suggestion.cs
Snyk.Code.Library/Service/AnalysisService.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/Service/SnykService.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/Service/SnykSolutionService.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/Service/VsCodeService.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/SnykCode/DataFlowStepsControl.xaml.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/SnykToolWindowControl.xaml.cs

Fix issue with open file on tree node click.

[ROAD-301] Fix: open file on tree node select

---

Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/SnykToolWindowControl.xaml.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Tree/SnykFilterableTree.xaml.cs

Fix duplicate results for OSS in tree issue.

[ROAD-286] Fix OSS duplicate results 

---

Snyk.Code.Library.Tests/SnykCode/SnykCodeServiceTest.cs
Snyk.Code.Library/Domain/SnykCodeError.cs
Snyk.Code.Library/Service/ISnykCodeService.cs
Snyk.Code.Library/Service/SnykCodeService.cs
Snyk.Code.Library/Snyk.Code.Library.csproj
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/Service/SnykTasksService.cs

[ROAD-247] Fix SnykCode error display

---

Snyk.Code.Library/Api/SnykCodeClient.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/Service/SnykService.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/Settings/SnykGeneralOptionsDialogPage.cs

Fix change user token and url in SnykCodeClient if user update Extension Settings.

[ROAD-302] Fix/update snykcode params on settings update

---

Snyk.VisualStudio.Extension/Snyk.VisualStudio.Extension.csproj
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/Commands/SnykScanCommand.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/Service/Domain/FeaturesSettings.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/Service/SnykService.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/Service/SnykTasksService.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/SnykAnalytics/AnalysisType.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/SnykAnalytics/AnalyticsAnalysisResult.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/SnykAnalytics/IssueType.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/SnykAnalytics/SnykAnalyticsService.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/MessagePanel.xaml.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/SnykToolWindowControl.xaml
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/SnykToolWindowControl.xaml.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Tree/SnykFilterableTree.xaml.cs

Update OSS analytics events and add events for SnykCode.

[ROAD-266] Feat: add analytics events for snykcode

---

.gitignore
Snyk.VisualStudio.Extension/source.extension.vsixmanifest

Update extension description to fit within marketplace view, when searching from Visual Studio and make it consistent with VS Code extension.

refactor: update extension description

---

.github/workflows/build.yml

Add tests run action in Github workflow

feat✨: add tests run GitHub action [ROAD-213]

---

Snyk.Code.Library.Tests/SnykCode/BundleServiceTest.cs
Snyk.Code.Library.Tests/SnykCode/CodeCacheServiceTest.cs
Snyk.Code.Library.Tests/SnykCode/SnykCodeServiceTest.cs
Snyk.Code.Library/Api/Dto/ExtendBundleRequestDto.cs
Snyk.Code.Library/Api/ISnykCodeClient.cs
Snyk.Code.Library/Api/SnykCodeClient.cs
Snyk.Code.Library/Service/BundleService.cs
Snyk.Code.Library/Service/CodeCacheService.cs
Snyk.Code.Library/Service/CodeServiceFactory.cs
Snyk.Code.Library/Service/FiltersService.cs
Snyk.Code.Library/Service/IBundleService.cs
Snyk.Code.Library/Service/ICodeCacheService.cs
Snyk.Code.Library/Service/IFileProvider.cs
Snyk.Code.Library/Service/IFiltersService.cs
Snyk.Code.Library/Service/SnykCodeFileProvider.cs
Snyk.Code.Library/Service/SnykCodeService.cs
Snyk.Code.Library/Snyk.Code.Library.csproj
Snyk.Common/CollectionExtensions.cs
Snyk.Common/FileUtil.cs
Snyk.Common/ISolutionService.cs
Snyk.Common/Snyk.Common.csproj
Snyk.VisualStudio.Extension/Snyk.VisualStudio.Extension.csproj
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/Service/SnykService.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/Service/SnykSolutionService.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/Service/SnykTasksService.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/Service/SnykVsSolutionLoadEvents.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/SnykCode/CodeCacheHierarchyEvents.cs

Added cache functionality for SnykCode.

feat: ✨ snykcode cache [ROAD-204]

---

Snyk.Code.Library.Tests/SnykCode/AnalysisServiceTest.cs
Snyk.Code.Library.Tests/SnykCode/BundleServiceTest.cs
Snyk.Code.Library.Tests/SnykCode/SnykCodeClientTest.cs
Snyk.Code.Library.Tests/SnykCode/SnykCodeServiceTest.cs
Snyk.Code.Library/Api/Dto/Analysis/AnalysisResultDto.cs
Snyk.Code.Library/Api/Dto/Analysis/AnalysisResultKeyDto.cs
Snyk.Code.Library/Api/Dto/Analysis/AnalysisResultRequestDto.cs
Snyk.Code.Library/Api/Dto/BundleResponseDto.cs
Snyk.Code.Library/Api/Dto/CodeFileDto.cs
Snyk.Code.Library/Api/Dto/UploadFilesExtendBundleRequestDto.cs
Snyk.Code.Library/Api/ISnykCodeClient.cs
Snyk.Code.Library/Api/SnykCodeClient.cs
Snyk.Code.Library/Domain/Analysis/AnalysisStatus.cs
Snyk.Code.Library/Service/AnalysisService.cs
Snyk.Code.Library/Service/BundleService.cs
Snyk.Code.Library/Service/CodeCacheService.cs
Snyk.Code.Library/Service/IBundleService.cs
Snyk.Code.Library/Service/ICodeCacheService.cs
Snyk.Code.Library/Service/IFileProvider.cs
Snyk.Code.Library/Service/SnykCodeFileProvider.cs
Snyk.Code.Library/Snyk.Code.Library.csproj

Replace old SnykCode API endpoints with new one.
Bundle payload without files property.
Removed /file endpoint.
Changed get analysis payload.
Files content uploaded via extend bundle endpoint.

Feat: ✨ support new code api endpoints

---

Snyk.VisualStudio.Extension/Snyk.VisualStudio.Extension.csproj
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/ManualAssemblyResolver.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/SnykVSPackage.cs

Added listener to load missing assemblies.

Fix 🐛 VS2015 and VS2017 support [ROAD-372]

---

Snyk.Code.Library.Tests/SnykCode/SnykCodeClientTest.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/Settings/SnykGeneralSettingsUserControl.Designer.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Notifications/VsInfoBarService.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/SnykToolWindowControl.xaml.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Tree/RootTreeNode.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Tree/SnykFilterableTree.xaml

1. ✅ Tree tree node labels. Labels changed it to "disabled, enable in Settings".
2. ✅ Fixed information bar icon. Not it's error icon.
3. ✅ Fix display tooltip in Settings.
4. ✅ Fixed SnykCode results duplicated in tree.

Fix: 🐛 UI issues and improvements [ROAD-533]

---

Snyk.Code.Library.Tests/SnykCode/AnalysisServiceTest.cs
Snyk.Code.Library.Tests/SnykCode/BundleServiceTest.cs
Snyk.Code.Library.Tests/SnykCode/CodeCacheServiceTest.cs
Snyk.Code.Library.Tests/SnykCode/SnykCodeServiceTest.cs
Snyk.Code.Library/Service/AnalysisService.cs
Snyk.Code.Library/Service/BundleService.cs
Snyk.Code.Library/Service/CodeCacheService.cs
Snyk.Code.Library/Service/CodeServiceFactory.cs
Snyk.Code.Library/Service/IAnalysisService.cs
Snyk.Code.Library/Service/IBundleService.cs
Snyk.Code.Library/Service/ISnykCodeService.cs
Snyk.Code.Library/Service/SnykCodeEventArgs.cs
Snyk.Code.Library/Service/SnykCodeScanState.cs
Snyk.Code.Library/Service/SnykCodeService.cs
Snyk.Code.Library/Snyk.Code.Library.csproj
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/Service/SnykService.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/SnykVSPackage.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Notifications/VsStatusBar.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Notifications/VsStatusBarNotificationService.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/SnykToolWindowControl.xaml.cs

Added events to display scan progress on SnykCode scan. Now in status bar it shows "Prepare 5%" and "Analysing 46%".

Feat ✨ SnykCode progress [ROAD-325]

---

Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/Commands/SnykScanCommand.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/DownloadState.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/MessagePanel.xaml
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/OverviewState.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/RunScanState.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/ScanResultsState.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/SnykToolWindowControl.xaml.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/UpdateDownloadState.cs

Fixed disable/enable button on tool window main panel with run scan button on toolbar.

Fix: sync run buttons [ROAD-507]

---

Snyk.VisualStudio.Extension/Snyk.VisualStudio.Extension.csproj
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/CLI/Download/SnykCliDownloader.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/Settings/SnykProjectOptionsUserControl.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/Settings/SnykProjectSettings.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/Settings/SnykSettings.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/Settings/SnykSettingsLoader.cs
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/Settings/SnykUserStorageSettingsService.cs

Fix issue with broken settings for project/solution. Now settings for solution saved and don't lost.

Fix 🐛 broken settings issue [ROAD-466]

---

.gitignore
Snyk.Common/LogManager.cs
Snyk.Common/Snyk.Common.csproj
Snyk.Common/SnykAppSettings.cs
Snyk.Common/SnykExtension.cs
Snyk.Common/packages.config
Snyk.VisualStudio.Extension/Snyk.VisualStudio.Extension.csproj
Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/SnykAnalytics/SnykAnalyticsService.cs

Added Sentry error reporting support.

Feat: ✨sentry error reporting [ROAD-364]

---

Snyk.Code.Library.Tests/Snyk.Code.Library.Tests.csproj
Snyk.Code.Library.Tests/SnykCode/BundleServiceTest.cs
Snyk.Code.Library.Tests/SnykCode/FiltersServiceTest.cs
Snyk.Code.Library.Tests/SnykCode/SnykCodeClientTest.cs
Snyk.Code.Library/Api/Dto/Analysis/CoverageDto.cs
Snyk.Code.Library/Api/Dto/Analysis/MarkerDto.cs
Snyk.Code.Library/Api/Dto/BundleResponseDto.cs
Snyk.Code.Library/Api/Dto/CodeFileDto.cs
Snyk.Code.Library/Api/SnykCodeClient.cs
Snyk.Code.Library/Service/AnalysisService.cs
Snyk.Code.Library/Service/BundleService.cs
Snyk.Code.Library/Service/FiltersService.cs
Snyk.Code.Library/Snyk.Code.Library.csproj
Snyk.Code.Library/packages.config
Snyk.Common/Json.cs
Snyk.Common/Snyk.Common.csproj
Snyk.Common/appsettings.json
Snyk.Common/packages.config
Snyk.VisualStudio.Extension.2022/Snyk.VisualStudio.Extension.2022.csproj
Snyk.VisualStudio.Extension.Shared/Snyk/VisualStudio/Extension/CLI/CLIError.cs
Snyk.VisualStudio.Extension.Shared/Snyk/VisualStudio/Extension/CLI/Download/LatestReleaseInfo.cs
Snyk.VisualStudio.Extension.Shared/Snyk/VisualStudio/Extension/SnykVSPackage.cs
Snyk.VisualStudio.Extension.Tests/Snyk.VisualStudio.Extension.Tests.csproj
Snyk.VisualStudio.Extension/Snyk.VisualStudio.Extension.csproj
Snyk.VisualStudio.Extension/packages.config
Snyk.VisualStudio.Extension/source.extension.vsixmanifest

Fix issues when scan large projects.

Fix: 🐛 scan large projects

---

Snyk.VisualStudio.Extension.Shared/Snyk/VisualStudio/Extension/UI/Tree/SnykFilterableTree.xaml

Add auto expand tree items by default

fix: add auto expand tree items

---

Snyk.VisualStudio.Extension.Shared/Snyk/VisualStudio/Extension/CLI/SnykConsoleRunner.cs
Snyk.VisualStudio.Extension.Shared/Snyk/VisualStudio/Extension/UI/Tree/SnykFilterableTree.xaml

Fix snyk token for CLI.
Fix tree view in dark mode.

fix: issues with tree view and snyk token

---

Snyk.VisualStudio.Extension.Shared/Snyk/VisualStudio/Extension/Settings/SnykSettingsLoader.cs

Add check if settings file exists before load it.

fix: check before load settings file

---

Snyk.Common/Guid.cs
Snyk.Common/Snyk.Common.csproj
Snyk.VisualStudio.Extension.Shared/CLI/Download/SnykCliDownloader.cs
Snyk.VisualStudio.Extension.Shared/CLI/InvalidTokenException.cs
Snyk.VisualStudio.Extension.Shared/CLI/SnykCli.cs
Snyk.VisualStudio.Extension.Shared/Service/SnykService.cs
Snyk.VisualStudio.Extension.Shared/Service/SnykTasksService.cs
Snyk.VisualStudio.Extension.Shared/Settings/SnykGeneralSettingsUserControl.cs
Snyk.VisualStudio.Extension.Shared/Snyk.VisualStudio.Extension.Shared.projitems
Snyk.VisualStudio.Extension.Shared/SnykAnalytics/SnykAnalyticsService.cs
Snyk.VisualStudio.Extension.Shared/SnykVSPackage.cs
Snyk.VisualStudio.Extension.Shared/UI/Notifications/NotificationService.cs
Snyk.VisualStudio.Extension.Shared/UI/Notifications/VsInfoBarService.cs
Snyk.VisualStudio.Extension.Shared/UI/Notifications/VsStatusBarNotificationService.cs
Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/MessagePanel.xaml
Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/MessagePanel.xaml.cs
Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/OverviewState.cs
Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/SnykToolWindowCommand.cs
Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/SnykToolWindowControl.xaml.cs
Snyk.VisualStudio.Extension.Tests/SnykCliTest.cs

This PR fix next issues:
* if snyk code disabled and os scan fail with error
* if no cli file show overview
* if cli file broken show error message in overview panel
* show overview after cli download
* download cli in settings and show run scan message

[ROAD-351] Fix:  📺   screens workflow

---

Snyk.VisualStudio.Extension.2022/source.extension.vsixmanifest
Snyk.VisualStudio.Extension/source.extension.vsixmanifest

chore: update extension version

---

Snyk.VisualStudio.Extension.2022/source.extension.vsixmanifest

Restore correct product id (extension id) for 2022 vsix file

fix: product id (extension id) for 2022 vsix file

---

Snyk.VisualStudio.Extension.2022/source.extension.vsixmanifest
Snyk.VisualStudio.Extension.Shared/CLI/ICli.cs
Snyk.VisualStudio.Extension.Shared/CLI/SnykCli.cs
Snyk.VisualStudio.Extension.Shared/Cache/AbstractCacheHierarchyEvents.cs
Snyk.VisualStudio.Extension.Shared/Cache/CodeCacheHierarchyEvents.cs
Snyk.VisualStudio.Extension.Shared/Cache/OssCacheHierarchyEvents.cs
Snyk.VisualStudio.Extension.Shared/Service/IOssService.cs
Snyk.VisualStudio.Extension.Shared/Service/ISnykServiceProvider.cs
Snyk.VisualStudio.Extension.Shared/Service/OssScanException.cs
Snyk.VisualStudio.Extension.Shared/Service/OssService.cs
Snyk.VisualStudio.Extension.Shared/Service/SnykService.cs
Snyk.VisualStudio.Extension.Shared/Service/SnykSolutionService.cs
Snyk.VisualStudio.Extension.Shared/Service/SnykTasksService.cs
Snyk.VisualStudio.Extension.Shared/Service/SnykVsSolutionLoadEvents.cs
Snyk.VisualStudio.Extension.Shared/Snyk.VisualStudio.Extension.Shared.projitems
Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/SnykToolWindowControl.xaml.cs
Snyk.VisualStudio.Extension.Tests/OssServiceTest.cs
Snyk.VisualStudio.Extension/source.extension.vsixmanifest
snyk-visual-studio-plugin.sln

Added cache for Open Source Security. If no changes in manifest files extension will return cached value.

[ROAD-322] Feat/add oss cache

---

Snyk.VisualStudio.Extension.2022/Snyk.VisualStudio.Extension.2022.csproj
Snyk.VisualStudio.Extension.Shared/Service/SnykService.cs
Snyk.VisualStudio.Extension.Shared/Service/SnykTasksService.cs
Snyk.VisualStudio.Extension.Shared/SnykVSPackage.cs
Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/OssDescriptionControl.xaml.cs
Snyk.VisualStudio.Extension/Snyk.VisualStudio.Extension.csproj

Added additional try-catch blocks

[ROAD-442] Fix/improve exceptions handling

---

Snyk.VisualStudio.Extension.2022/source.extension.vsixmanifest
Snyk.VisualStudio.Extension/source.extension.vsixmanifest

chore: updated version

---

Snyk.Common/ISolutionService.cs
Snyk.VisualStudio.Extension.Shared/Service/SnykTasksService.cs
Snyk.VisualStudio.Extension.Shared/Settings/SnykSolutionOptionsUserControl.cs

Restore proper logic for check is solution open or not.

fix: restore proper logic for solution open check

---

CHANGELOG.md
Snyk.VisualStudio.Extension.Shared/Service/SnykSolutionService.cs
Snyk.VisualStudio.Extension.Shared/Service/SnykVsSolutionLoadEvents.cs

Fix issue with cache invalidate if solution switch to another. For this added clear OSS cache method call on different solution events.

[ROAD-823] fix: invalidate cache if solution switch

---

Snyk.VisualStudio.Extension.2022/vs-publish.json
Snyk.VisualStudio.Extension/vs-publish.json

Fixes failing release pipeline.

fix: path to overview file

---

CHANGELOG.md
Snyk.Code.Library/Domain/Analysis/Suggestion.cs
Snyk.Code.Library/Service/AnalysisService.cs
Snyk.VisualStudio.Extension.Shared/CLI/Severity.cs
Snyk.VisualStudio.Extension.Shared/CLI/Vulnerability.cs
Snyk.VisualStudio.Extension.Shared/Model/Severity.cs
Snyk.VisualStudio.Extension.Shared/Snyk.VisualStudio.Extension.Shared.projitems
Snyk.VisualStudio.Extension.Shared/UI/SeverityFilter.cs
Snyk.VisualStudio.Extension.Shared/UI/SnykIconProvider.cs
Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/DescriptionHeaderPanel.xaml.cs
Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/SnykToolWindow.cs
Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/SnykToolWindowControl.xaml.cs
Snyk.VisualStudio.Extension.Shared/UI/Tree/SnykFilterableTree.xaml.cs
Snyk.VisualStudio.Extension.Tests/SnykCliTest.cs

Fixed Snyk-Code severities being off by one (High would show as Medium, etc...)

[ROAD-831] fix: Wrong severity icons in snyk code

---

Snyk.VisualStudio.Extension/source.extension.vsixmanifest

Fixes wrong installation target in manifest file.

fix: VSIX 2015-2019 installation target

---

CHANGELOG.md
Snyk.Code.Library.Tests/SnykCode/AnalysisServiceTest.cs
Snyk.Code.Library.Tests/SnykCode/BundleServiceTest.cs
Snyk.Code.Library.Tests/SnykCode/CodeCacheServiceTest.cs
Snyk.Code.Library.Tests/SnykCode/FiltersServiceTest.cs
Snyk.Code.Library.Tests/SnykCode/SnykCodeServiceTest.cs
Snyk.Code.Library/Service/CodeCacheService.cs
Snyk.Code.Library/Service/ICodeCacheService.cs
Snyk.Code.Library/Service/SnykCodeFileProvider.cs
Snyk.Code.Library/Service/SnykCodeService.cs
Snyk.Common/IFileProvider.cs
Snyk.Common/ISolutionService.cs
Snyk.VisualStudio.Extension.Shared/CLI/ICli.cs
Snyk.VisualStudio.Extension.Shared/CLI/SnykCli.cs
Snyk.VisualStudio.Extension.Shared/Service/IOssService.cs
Snyk.VisualStudio.Extension.Shared/Service/OssService.cs
Snyk.VisualStudio.Extension.Shared/Service/SnykSolutionService.cs
Snyk.VisualStudio.Extension.Shared/Service/SnykTasksService.cs
Snyk.VisualStudio.Extension.Shared/Settings/ISnykOptions.cs
Snyk.VisualStudio.Extension.Shared/Settings/SnykGeneralOptionsDialogPage.cs
Snyk.VisualStudio.Extension.Shared/Settings/SnykSolutionOptionsUserControl.cs
Snyk.VisualStudio.Extension.Shared/Settings/SnykUserStorageSettingsService.cs
Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/SnykCode/DataFlowStepsControl.xaml.cs
Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/SnykCode/SnykCodeDescriptionControl.xaml.cs
Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/SnykToolWindowControl.xaml.cs
Snyk.VisualStudio.Extension.Tests/OssServiceTest.cs
Snyk.VisualStudio.Extension.Tests/SnykCliTest.cs
Snyk.VisualStudio.Extension.Tests/SnykSolutionServiceTest.cs
Snyk.VisualStudio.Extension.Tests/SnykUserStorageSettingsServiceTest.cs

Before this changes root directory for cli scan calculated using solution file. Now extension will get solution file and check is it root directory for solution file and other projects. If not root directory for all projects in solution it will find parent root directory for all projects in solution. 
Because now this method is using async/await changes affected other files.
- ✅ Tests added and all succeed
- ✅ Linted
- ✅ CHANGELOG.md updated
- ☑️ README.md updated, if user-facing
Example of project with solution file not in root directory.

[ROAD-833] Fix: open source scan issues - fixed root directory for scan calculation

---

Snyk.Code.Library/Service/SnykCodeService.cs
Snyk.VisualStudio.Extension.Shared/Service/SnykSolutionService.cs

Fix scan complex solution structure with VS2015.
- :white_check_mark: Tests added and all succeed
- :white_check_mark: Linted
- :white_check_mark: CHANGELOG.md updated
- :white_check_mark: README.md updated, if user-facing

[ROAD-833] fix: complex solution oss scan in vs2015 and updated vsix version

---

CHANGELOG.md
Snyk.Code.Library.Tests/SnykCode/SnykCodeClientTest.cs
Snyk.Code.Library/Api/Dto/Analysis/AnalysisContextDto.cs
Snyk.Code.Library/Api/Dto/Analysis/AnalysisResultRequestDto.cs
Snyk.Code.Library/Api/Dto/Analysis/CoverageDto.cs
Snyk.Code.Library/Api/ISnykCodeClient.cs
Snyk.Code.Library/Api/SnykCodeClient.cs
Snyk.Code.Library/Service/CodeServiceFactory.cs
Snyk.Code.Library/Snyk.Code.Library.csproj
Snyk.VisualStudio.Extension.Shared/Service/SnykService.cs
Snyk.VisualStudio.Extension.Shared/Settings/SnykGeneralOptionsDialogPage.cs

Added analysisContext information (flow and client's organization name) to analysis request.

[ROAD-811] feat: added analysisContext to analysis requests

---

CHANGELOG.md
Snyk.VisualStudio.Extension.2022/source.extension.vsixmanifest
Snyk.VisualStudio.Extension.Shared/Service/SnykCliScanEventArgs.cs
Snyk.VisualStudio.Extension.Shared/Service/SnykTasksService.cs
Snyk.VisualStudio.Extension.Shared/Settings/SnykGeneralOptionsDialogPage.cs
Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/SnykToolWindowControl.xaml.cs
Snyk.VisualStudio.Extension/source.extension.vsixmanifest

1. Fixed display proper message if error occurs.
2. Fixed issue with link to configure Snyk Code on web (found it while working on first item)

[ROAD-762]fix: display message on main panel if error occurs

---

.github/workflows/release.yml

Fixed secrets missing from the release pipeline

fix: add missing environment parameter

---

CHANGELOG.md
Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/MessagePanel.xaml
Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/MessagePanel.xaml.cs

…ervice links
Changed Welcome screen text. And added privacy policy, term of service links.

[ROAD-839] feat: change welcome screen text and add privacy policy, term of service links

---

Snyk.Common/LogManager.cs
Snyk.Common/Snyk.Common.csproj
Snyk.Common/SnykExtension.cs
Snyk.Common/appsettings.development.json
Snyk.VisualStudio.Extension.Shared/SnykAnalytics/SnykAnalyticsService.cs

Added an appsettings.development.json file for debug mode.

[ROAD-764] Refactor: add devlopment appsettings

---

CHANGELOG.md
Snyk.VisualStudio.Extension.2022/source.extension.vsixmanifest
Snyk.VisualStudio.Extension/source.extension.vsixmanifest

Fixes config issues with Snyk Code and Sentry environments.

chore: release 1.1.13

---

.github/workflows/readme-sync.yml

Workflow that synchronises readme.md from Snyk Docs.

feat: synchronise Readme from Snyk Docs [ROAD-775]

---

CHANGELOG.md
Snyk.Code.Library.Tests/SnykCode/DcIgnoreServiceTest.cs
Snyk.Code.Library/Resources/full.dcignore

Removed rule because of which no files for underscore folder after filtering using dcignore file.

[ROAD-901] fix: no supported code available issue

---

CHANGELOG.md
Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/SnykCode/DataFlowStepsControl.xaml
Snyk.VisualStudio.Extension.Shared/UI/Tree/SnykFilterableTree.xaml

Fixed a bug where the color of the text in the tree view did not match the color from VS theme.

fix: text color in tree view issues

---

CHANGELOG.md
Snyk.Analytics/SnykAnalyticsService.cs

Fixed an error when clicking on issues with unknown severity in the tool window

fix: removed exception when severity is unknown

---

Snyk.Analytics/SnykAnalyticsService.cs

Fixed event not being sent to Analytics service

fix: issue-in-tree-is-clicked events not being sent

---

Snyk.VisualStudio.Extension.Shared/UI/Tree/SnykFilterableTree.xaml

Fixed the color of the tree item when unfocused

fix: wrong color in tree view item

---

CHANGELOG.md
Snyk.VisualStudio.Extension.Shared/CLI/Vulnerability.cs
Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/OssDescriptionControl.xaml
Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/OssDescriptionControl.xaml.cs

Replace the word `Remediation` with `Fix` for consistency

refactor: Replace "Remediation" with "Fix" in OSS report

---

CHANGELOG.md
Snyk.VisualStudio.Extension.Shared/CLI/ICli.cs
Snyk.VisualStudio.Extension.Shared/CLI/SnykCli.cs
Snyk.VisualStudio.Extension.Shared/Service/SnykSolutionService.cs
Snyk.VisualStudio.Extension.Shared/Settings/SnykGeneralOptionsDialogPage.cs
Snyk.VisualStudio.Extension.Shared/Settings/SnykGeneralSettingsUserControl.Designer.cs
Snyk.VisualStudio.Extension.Shared/Settings/SnykGeneralSettingsUserControl.cs
Snyk.VisualStudio.Extension.Tests/GeneralOptionsDialogPage.cs

Fixed custom endpoint changing leading to authentication errors

[ROAD-1017] Fix: Custom endpoint settings

---

CHANGELOG.md
Snyk.VisualStudio.Extension/Snyk.VisualStudio.Extension.csproj

Fixed missing dependencies on VS2017

[ROAD-1040] fix: missing dependencies on VS2017

---

.github/workflows/readme-sync.yml

Enable automatic signing commits issued by actions bot for readme sync.
Example PRs: https://github.com/snyk/vscode-extension/pull/264
https://github.com/snyk/snyk-visual-studio-plugin/pull/201

feat: sign commits on docs sync [ROAD-931]

---

.github/workflows/release.yml

Removed the weekly release automation

chore: removed scheduled release

---

CHANGELOG.md
README.md
Snyk.VisualStudio.Extension.Shared/Settings/SnykGeneralSettingsUserControl.Designer.cs

_Updated wording in menu settings for collecting analytics. This is so that it will be consistent across all support platforms_

chore: update wording for collecting analytics

---

.github/workflows/readme-sync.yml

fix: readme sync [ROAD-1104]

---

CHANGELOG.md
Snyk.VisualStudio.Extension.2022/Snyk.VisualStudio.Extension.2022.csproj
Snyk.VisualStudio.Extension.Shared/Service/SnykTasksService.cs

Fixed errors during extension loading in VS2022 extension

Fix: VS 2022 errors

---

Snyk.Code.Library.Tests/SnykCode/DcIgnoreServiceTest.cs
Snyk.Code.Library/Service/DcIgnoreService.cs
Snyk.Code.Library/Service/IDcIgnoreService.cs

Fixed a bug leading to files not being scanned by Snyk Code due to full paths being checked against `.gitignore`/`.dcignore`.

fix: code scans missing files

---

CHANGELOG.md

Updated changelog for 1.1.28 release

docs: updated changelog

---

Snyk.VisualStudio.Extension.Shared/UI/Notifications/VsInfoBarService.cs

Replaced the "Submit an issue" link in the error notification bar with a link to support.

fix: replace issues link with support link [ROAD-1201]

---

CHANGELOG.md
Snyk.VisualStudio.Extension.2022/Snyk.VisualStudio.Extension.2022.csproj
Snyk.VisualStudio.Extension.2022/TrustDialogWindow.xaml
Snyk.VisualStudio.Extension.2022/TrustDialogWindow.xaml.cs
Snyk.VisualStudio.Extension.Shared/Service/ISnykServiceProvider.cs
Snyk.VisualStudio.Extension.Shared/Service/IWorkspaceTrustService.cs
Snyk.VisualStudio.Extension.Shared/Service/SnykService.cs
Snyk.VisualStudio.Extension.Shared/Service/SnykTasksService.cs
Snyk.VisualStudio.Extension.Shared/Service/WorkspaceTrustService.cs
Snyk.VisualStudio.Extension.Shared/Settings/IUserStorageSettingsService.cs
Snyk.VisualStudio.Extension.Shared/Settings/SnykSettings.cs
Snyk.VisualStudio.Extension.Shared/Settings/SnykUserStorageSettingsService.cs
Snyk.VisualStudio.Extension.Shared/Snyk.VisualStudio.Extension.Shared.projitems
Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/MessagePanel.xaml
Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/MessagePanel.xaml.cs
Snyk.VisualStudio.Extension.Tests/Service/WorkspaceTrustServiceTest.cs
Snyk.VisualStudio.Extension/Snyk.VisualStudio.Extension.csproj
Snyk.VisualStudio.Extension/TrustDialogWindow.xaml
Snyk.VisualStudio.Extension/TrustDialogWindow.xaml.cs

Adds workspace trust mechanism to ensure scans are run on the trusted projects.

feat: add workspace trust

---

CHANGELOG.md
Snyk.Code.Library/Service/FiltersService.cs
Snyk.VisualStudio.Extension.2022/Snyk.VisualStudio.Extension.2022.csproj
Snyk.VisualStudio.Extension.2022/TrustDialogWindow.xaml
Snyk.VisualStudio.Extension.2022/source.extension.vsixmanifest
Snyk.VisualStudio.Extension.Shared/Service/SnykTasksService.cs
Snyk.VisualStudio.Extension/TrustDialogWindow.xaml

- Added support for ARM64 processors
- Snyk code no longer filters configuration files
- Fixed trust dialog in older VS versions

fix: Snyk Code configuration filtering & arm 64 support

---

Snyk.Code.Library.Tests/SnykCode/Api/SnykCodeClientTest.cs
Snyk.Code.Library.Tests/SnykCode/TestSettings.cs
Snyk.VisualStudio.Extension.Tests/SnykApiServiceTest.cs

Updates token to the Hammerhead org owned one. Pointing to prod for the org ownership reasons.
TestSettings.cs should be ideally shared by all projects, however wanted to keep the change scope to a bare minimum.

fix: code tests

---

Snyk.Common/HttpClientFactory.cs

Update AuthN header for Snyk Code to align with Snyk Engineering guidelines.

chore: update AuthN header for snyk code

---

.github/workflows/release.yml

Fix the reference to the integration tests workflow

fix: workflow reference path

---

.github/workflows/pr-workflow.yml
.github/workflows/release.yml
Snyk.Code.Library/Api/SnykCodeClient.cs

Log Snyk Code errors before throwing an exception

chore: add logging before throwing exception

---

Snyk.Code.Library.Tests/SnykCode/AnalysisServiceTest.cs
Snyk.Code.Library.Tests/SnykCode/SnykCodeServiceTest.cs
Snyk.Code.Library/Service/AnalysisService.cs
Snyk.Code.Library/Service/IAnalysisService.cs

Increase Snyk Code client side timeout

fix: Increase Snyk code client side timeout [SUP-1598]

---

CHANGELOG.md
Snyk.VisualStudio.Extension.Shared/CLI/SnykCli.cs
Snyk.VisualStudio.Extension.Shared/Settings/ErrorProviderExtensions.cs
Snyk.VisualStudio.Extension.Shared/Settings/SnykGeneralOptionsDialogPage.cs
Snyk.VisualStudio.Extension.Shared/Settings/SnykGeneralSettingsUserControl.Designer.cs
Snyk.VisualStudio.Extension.Shared/Settings/SnykGeneralSettingsUserControl.cs
Snyk.VisualStudio.Extension.Shared/Snyk.VisualStudio.Extension.Shared.projitems

Custom endpoints validation in the settings page did not work correctly and led to crashes.

fix: Custom Endpoint URL crash [HEAD-536]

---

CHANGELOG.md
README.md
Snyk.VisualStudio.Extension.2022/source.extension.vsixmanifest
Snyk.VisualStudio.Extension.Shared/README.md
Snyk.VisualStudio.Extension.Shared/index.html
Snyk.VisualStudio.Extension/source.extension.vsixmanifest

https://snyksec.atlassian.net/browse/IDE-189
This PR shortens the name of the plugin to just "Snyk Security"
This change is based on multiple complaints from the field and customers.

[IDE-189] fix: shortened plugin's name to just Snyk Security

---

CHANGELOG.md
Snyk.Analytics/Snyk.Analytics.csproj
Snyk.VisualStudio.Extension.2022/Snyk.VisualStudio.Extension.2022.csproj
Snyk.VisualStudio.Extension/Snyk.VisualStudio.Extension.csproj

fix: upgrade analytics dependency

---

Snyk.Code.Library/Snyk.Code.Library.csproj
Snyk.Common/Authentication/AuthenticationToken.cs
Snyk.Common/Authentication/OAuthToken.cs
Snyk.Common/HttpClientFactory.cs
Snyk.Common/Snyk.Common.csproj
Snyk.VisualStudio.Extension.Shared/Settings/ErrorProviderExtensions.cs
Snyk.VisualStudio.Extension.Shared/Settings/SnykGeneralOptionsDialogPage.cs
Snyk.VisualStudio.Extension.Shared/analytics/ScanDoneEvent.cs
Snyk.VisualStudio.Extension.Shared/analytics/SnykIdeAnalyticsService.cs
Snyk.VisualStudio.Extension/Properties/AssemblyInfo.cs

- Remove direct reference for System.Text.Json.
- Add binding redirect System.Diagnostics.DiagnosticSource because of an issue in new Serilog version.
- Refactor usage for System.Text.Json to use Newtonsoft.Json

fix: old IDE support

---

CHANGELOG.md
Snyk.VisualStudio.Extension.Shared/analytics/ScanDoneEvent.cs
Snyk.VisualStudio.Extension.Tests/analytics/SnykIDEAnalyticsServiceTest.cs

fix: scan done status

---

CHANGELOG.md
Snyk.Common/Service/ApiEndpointResolver.cs
Snyk.VisualStudio.Extension.Shared/Settings/SnykGeneralOptionsDialogPage.cs
Snyk.VisualStudio.Extension.Tests/GeneralOptionsDialogPage.cs

- Change Default Endpoint to be api.snyk.io
- Refactor logic that determines deeproxy and app endpoint from api endpoint.

refactor: change default API endpoint [IDE-129]

---

Snyk.Common/Service/ApiEndpointResolver.cs
Snyk.VisualStudio.Extension.Shared/Settings/SnykGeneralOptionsDialogPage.cs
Snyk.VisualStudio.Extension.Tests/GeneralOptionsDialogPageTest.cs

refactor: transform persisted api custom endpoint to new schema

---

.github/workflows/build-project.yml
.github/workflows/integration-tests.yml
.github/workflows/pr-workflow.yml
.github/workflows/release.yml
Snyk.Common/Snyk.Common.csproj
Tests/Integration.Pre22.Tests/Integration.Pre22.Tests.csproj

feat: run integration tests on PR

---

.circleci/config.yml
catalog-info.yaml

chore: change ownership and alerts channel

---

.github/workflows/pr-workflow.yml
.github/workflows/security-scan-upload.yml
.snyk

Add qaulity gates for open source and code using snyk github actions.

chore: test github actions

---

CHANGELOG.md
README-LEGACY.md
Snyk.VisualStudio.Extension/vs-publish.json

chore: add deprecation notice for older version

---

.circleci/config.yml

Add quality gates in CircleCI config for better monitoring of repository.
Quality gates have been implemented fully via Github Actions in .github/workflows

chore: add quality gates in CircleCI config

---

Snyk.VisualStudio.Extension.2022/Settings/SnykGeneralSettingsUserControl.resx

fix: removed experimental disclaimer from using OAuth authentication method

fix: removed experimental disclaimer from using oauth method for authentication

---

CHANGELOG.md
Snyk.Common.Tests/Service/ApiEndpointResolverTest.cs
Snyk.Common/Authentication/AuthenticationType.cs

chore: change default auth type to be oauth

---

README-LEGACY.md

Since we still have some users on 2019, i got a push back from the Customer Support on the full deprecation just yet.
I'll have to provide more evidence to them.
In the meantime, we need to update its readme to encourage users to upgrade to the VS 2022 and to notify them, that there will be no new features in the version.

chore: updated README legacy for 2015-2019 with softer deprecation notice

---

.gitleaksignore
Snyk.VisualStudio.Extension.2022/Language/ILanguageClientManager.cs
Snyk.VisualStudio.Extension.2022/Language/LanguageClientHelper.cs
Snyk.VisualStudio.Extension.2022/Language/SnykLanguageClient.cs
Snyk.VisualStudio.Extension.2022/Language/SnykLanguageClientCustomTarget.cs
Snyk.VisualStudio.Extension.2022/Language/SnykLanguageServerEventArgs.cs
Snyk.VisualStudio.Extension.2022/Resources/SnykLsInit.cs
Snyk.VisualStudio.Extension.2022/Settings/SnykGeneralOptionsDialogPage.cs
Snyk.VisualStudio.Extension.2022/Settings/SnykGeneralSettingsUserControl.cs
Snyk.VisualStudio.Extension.2022/Snyk.VisualStudio.Extension.2022.csproj
Snyk.VisualStudio.Extension.2022/SnykVSPackage.cs
Snyk.VisualStudio.Extension.2022/UI/Toolwindow/MessagePanel.xaml.cs
Snyk.VisualStudio.Extension.2022/UI/Toolwindow/SnykToolWindowControl.xaml.cs

fix: ls doesn't init after extension loads [IDE-617]

---

Snyk.Common/Settings/ISnykOptions.cs
Snyk.VisualStudio.Extension.2022/Language/CustomInitializationOptions.cs
Snyk.VisualStudio.Extension.2022/Language/LspAnalysisResult.cs
Snyk.VisualStudio.Extension.2022/Language/SnykLanguageClient.cs
Snyk.VisualStudio.Extension.2022/Language/SnykLanguageClientCustomTarget.cs
Snyk.VisualStudio.Extension.2022/Service/Domain/FeaturesSettings.cs
Snyk.VisualStudio.Extension.2022/Service/SnykCodeScanEventArgs.cs
Snyk.VisualStudio.Extension.2022/Service/SnykTasksService.cs
Snyk.VisualStudio.Extension.2022/Service/SnykVsSolutionLoadEvents.cs
Snyk.VisualStudio.Extension.2022/Settings/SnykGeneralOptionsDialogPage.cs
Snyk.VisualStudio.Extension.2022/Settings/SnykGeneralSettingsUserControl.Designer.cs
Snyk.VisualStudio.Extension.2022/Settings/SnykGeneralSettingsUserControl.cs
Snyk.VisualStudio.Extension.2022/Settings/SnykGeneralSettingsUserControl.resx
Snyk.VisualStudio.Extension.2022/Settings/SnykSettings.cs
Snyk.VisualStudio.Extension.2022/Settings/SnykUserStorageSettingsService.cs
Snyk.VisualStudio.Extension.2022/Snyk.VisualStudio.Extension.2022.csproj
Snyk.VisualStudio.Extension.2022/UI/Html/BaseHtmlProvider.cs
Snyk.VisualStudio.Extension.2022/UI/Html/IacHtmlProvider.cs
Snyk.VisualStudio.Extension.2022/UI/Html/OssHtmlProvider.cs
Snyk.VisualStudio.Extension.2022/UI/Toolwindow/HtmlDescriptionPanel.xaml.cs
Snyk.VisualStudio.Extension.2022/UI/Toolwindow/SnykToolWindowControl.xaml.cs
Snyk.VisualStudio.Extension.2022/UI/Tree/IacVulnerabilityTreeNode.cs
Snyk.VisualStudio.Extension.2022/UI/Tree/SnykFilterableTree.xaml.cs
Snyk.VisualStudio.Extension.2022/UI/Tree/SnykIacFileTreeNode.cs

feat: IaC Scan

---

.github/workflows/build-project.yml

chore: update gh actions

---

.github/workflows/build-project.yml
.github/workflows/integration-tests.yml
.github/workflows/pr-workflow.yml
.github/workflows/release.yml

chore: update download-artifacts job

---

.github/workflows/release-preview.yml

feat: enable release publish

---

.github/actions/next-git-tag/patch-manifest.ps1

fix: set id attribute for preview

---

Snyk.Common/Settings/ISnykOptions.cs
Snyk.VisualStudio.Extension.2022/AuthDialogWindow.xaml
Snyk.VisualStudio.Extension.2022/AuthDialogWindow.xaml.cs
Snyk.VisualStudio.Extension.2022/Language/ILanguageClientManager.cs
Snyk.VisualStudio.Extension.2022/Language/LsAnalysisResult.cs
Snyk.VisualStudio.Extension.2022/Language/SnykLanguageClient.cs
Snyk.VisualStudio.Extension.2022/Language/SnykLanguageClientCustomTarget.cs
Snyk.VisualStudio.Extension.2022/Service/SnykTasksService.cs
Snyk.VisualStudio.Extension.2022/Settings/SnykGeneralOptionsDialogPage.cs
Snyk.VisualStudio.Extension.2022/Settings/SnykGeneralSettingsUserControl.Designer.cs
Snyk.VisualStudio.Extension.2022/Settings/SnykGeneralSettingsUserControl.cs
Snyk.VisualStudio.Extension.2022/Settings/SnykGeneralSettingsUserControl.resx
Snyk.VisualStudio.Extension.2022/Snyk.VisualStudio.Extension.2022.csproj
Snyk.VisualStudio.Extension.2022/SnykVSPackage.cs
Snyk.VisualStudio.Extension.2022/UI/Toolwindow/MessagePanel.xaml
Snyk.VisualStudio.Extension.2022/UI/Toolwindow/MessagePanel.xaml.cs
Snyk.VisualStudio.Extension.2022/UI/Toolwindow/SnykToolWindowControl.xaml.cs
Snyk.VisualStudio.Extension.2022/UI/Tree/OssVulnerabilityTreeNode.cs
Snyk.VisualStudio.Extension.2022/UI/Tree/SnykFilterableTree.xaml
Snyk.VisualStudio.Extension.2022/UI/Tree/SnykFilterableTree.xaml.cs

1. Added Init button to init state.
2. Implemented Authentication Window from IntelliJ
5. better handling for scanning now state (use same cancellation token).
6. fix horizontal jumpy tree
7. Enable LS trust.
8. Tree node logo for .ts files.

Fix: Auth login and UI issues

---

Snyk.Common/Settings/ISnykOptions.cs
Snyk.VisualStudio.Extension.2022/CLI/SnykCli.cs
Snyk.VisualStudio.Extension.2022/Download/SnykCliDownloader.cs
Snyk.VisualStudio.Extension.2022/Language/SnykLanguageClient.cs
Snyk.VisualStudio.Extension.2022/Service/SnykTasksService.cs
Snyk.VisualStudio.Extension.2022/Settings/SnykGeneralOptionsDialogPage.cs
Snyk.VisualStudio.Extension.2022/Settings/SnykGeneralSettingsUserControl.cs
Snyk.VisualStudio.Extension.2022/Snyk.VisualStudio.Extension.2022.csproj
Snyk.VisualStudio.Extension.2022/UI/Html/CodeHtmlProvider.cs
Snyk.VisualStudio.Extension.2022/UI/Toolwindow/HtmlDescriptionPanel.xaml
Snyk.VisualStudio.Extension.2022/UI/Toolwindow/HtmlDescriptionPanel.xaml.cs
Snyk.VisualStudio.Extension.2022/UI/Toolwindow/MessagePanel.xaml.cs
Snyk.VisualStudio.Extension.2022/UI/Toolwindow/SnykToolWindowControl.xaml.cs
Snyk.VisualStudio.Extension.2022/UI/Toolwindow/WebBrowserHostUIHandler.cs

* Disable Context menu, suppress JS errors and make the Html Viewer High DPI aware.
* Send default CLI Path if CLI Custom Path is empty
* Send didChangeConfiguration when folder is trusted for "Trust and Scan" flow.

fix: high dpi svg scaling

---

Snyk.VisualStudio.Extension.2022/UI/Toolwindow/MessagePanel.xaml

chore: change waiting text

---

Snyk.VisualStudio.Extension.2022/Language/LsConstants.cs

chore: bump ls protocol version to 16

---

CHANGELOG.md
Snyk.VisualStudio.Extension.2022/Language/ILanguageClientManager.cs
Snyk.VisualStudio.Extension.2022/Language/LsAnalysisResult.cs
Snyk.VisualStudio.Extension.2022/Language/LsConstants.cs
Snyk.VisualStudio.Extension.2022/Language/SnykLanguageClient.cs
Snyk.VisualStudio.Extension.2022/README.md
Snyk.VisualStudio.Extension.2022/UI/Toolwindow/SnykToolWindowControl.xaml.cs

feat: load issue html on demand

---

Snyk.VisualStudio.Extension.2022/Extension/JTokenExtension.cs
Snyk.VisualStudio.Extension.2022/Extension/UriExtensions.cs
Snyk.VisualStudio.Extension.2022/Language/SnykLanguageClientCustomTarget.cs
Snyk.VisualStudio.Extension.2022/Language/SnykLanguageClientMiddleware.cs
Snyk.VisualStudio.Extension.2022/Snyk.VisualStudio.Extension.2022.csproj
Snyk.VisualStudio.Extension.2022/UI/Tree/SnykFilterableTree.xaml.cs

fix: unc file paths

---

.snyk
Snyk.VisualStudio.Extension.2022/Theme/ThemeInfo.cs
Snyk.VisualStudio.Extension.2022/UI/Html/BaseHtmlProvider.cs
Snyk.VisualStudio.Extension.2022/UI/Html/CodeHtmlProvider.cs
Snyk.VisualStudio.Extension.2022/UI/Html/IacHtmlProvider.cs
Snyk.VisualStudio.Extension.2022/UI/Html/OssHtmlProvider.cs
Snyk.VisualStudio.Extension.2022/UI/Toolwindow/SnykToolWindowControl.xaml.cs

fix: styling across products

---

Snyk.Common/Settings/ISnykOptions.cs
Snyk.VisualStudio.Extension.2022/Download/SnykCliDownloader.cs
Snyk.VisualStudio.Extension.2022/Language/SnykLanguageClientCustomTarget.cs
Snyk.VisualStudio.Extension.2022/Settings/SnykGeneralOptionsDialogPage.cs
Snyk.VisualStudio.Extension.2022/Settings/SnykGeneralSettingsUserControl.cs
Snyk.VisualStudio.Extension.2022/UI/Notifications/NotificationService.cs
Snyk.VisualStudio.Extension.2022/UI/Notifications/VsInfoBarService.cs

feat: persist api url from LS after auth

---

Snyk.VisualStudio.Extension.2022/CLI/Download/SnykCliDownloader.cs

fix: update download endpoint

---

CHANGELOG.md
Snyk.Common/Settings/ISnykOptions.cs
Snyk.VisualStudio.Extension.2022/Analytics/AbstractAnalyticsEvent.cs
Snyk.VisualStudio.Extension.2022/Analytics/AnalyticsEvent.cs
Snyk.VisualStudio.Extension.2022/Analytics/AnalyticsSender.cs
Snyk.VisualStudio.Extension.2022/Language/ILanguageClientManager.cs
Snyk.VisualStudio.Extension.2022/Language/LsConstants.cs
Snyk.VisualStudio.Extension.2022/Language/SnykLanguageClient.cs
Snyk.VisualStudio.Extension.2022/Settings/SnykGeneralOptionsDialogPage.cs
Snyk.VisualStudio.Extension.2022/Settings/SnykSettings.cs
Snyk.VisualStudio.Extension.2022/Settings/SnykUserStorageSettingsService.cs
Snyk.VisualStudio.Extension.2022/Snyk.VisualStudio.Extension.2022.csproj

- adds a plugin installed event to be sent on startup (if not already sent before)

feat: add plugin installed analytics event [IDE-736]

---

.github/workflows/release-preview.yml
Snyk.VisualStudio.Extension.2022/Commands/AbstractSnykCommand.cs
Snyk.VisualStudio.Extension.2022/Commands/SnykCleanPanelCommand.cs
Snyk.VisualStudio.Extension.2022/Commands/SnykOpenSettingsCommand.cs
Snyk.VisualStudio.Extension.2022/Commands/SnykScanCommand.cs
Snyk.VisualStudio.Extension.2022/Commands/SnykStopCurrentTaskCommand.cs
Snyk.VisualStudio.Extension.2022/SnykVSPackage.cs
Snyk.VisualStudio.Extension.2022/UI/Toolwindow/SnykToolWindow.cs
Snyk.VisualStudio.Extension.2022/UI/Toolwindow/SnykToolWindowCommand.cs

fix: VS 17.10 compatibility

---

Snyk.VisualStudio.Extension.2022/UI/Html/BaseHtmlProvider.cs
Snyk.VisualStudio.Extension.2022/UI/Html/CodeHtmlProvider.cs

refactor: unify css or code

---

Snyk.VisualStudio.Extension.2022/Language/SnykLanguageClient.cs

fix: send correct integration info to analytics

---

Snyk.VisualStudio.Extension.2022/Snyk.VisualStudio.Extension.2022.csproj
Snyk.VisualStudio.Extension.2022/packages.lock.json

fix: add package-lock.json

---

Snyk.VisualStudio.Extension.2022/Commands/AbstractTaskCommand.cs
Snyk.VisualStudio.Extension.2022/Language/IJsonRpc.cs
Snyk.VisualStudio.Extension.2022/Language/ILanguageClientManager.cs
Snyk.VisualStudio.Extension.2022/Language/JsonRpcWrapper.cs
Snyk.VisualStudio.Extension.2022/Language/LanguageClientHelper.cs
Snyk.VisualStudio.Extension.2022/Language/LsSettings.cs
Snyk.VisualStudio.Extension.2022/Language/SnykLanguageClient.cs
Snyk.VisualStudio.Extension.2022/Language/SnykLanguageClientCustomTarget.cs
Snyk.VisualStudio.Extension.2022/Service/IFeatureFlagService.cs
Snyk.VisualStudio.Extension.2022/Service/ISnykServiceProvider.cs
Snyk.VisualStudio.Extension.2022/Service/SnykFeatureFlagService.cs
Snyk.VisualStudio.Extension.2022/Service/SnykService.cs
Snyk.VisualStudio.Extension.2022/Service/SnykTasksService.cs
Snyk.VisualStudio.Extension.2022/Settings/ISnykOptions.cs
Snyk.VisualStudio.Extension.2022/Settings/SnykGeneralOptionsDialogPage.cs
Snyk.VisualStudio.Extension.2022/Settings/SnykGeneralSettingsUserControl.cs
Snyk.VisualStudio.Extension.2022/Snyk.VisualStudio.Extension.2022.csproj
Snyk.VisualStudio.Extension.2022/SnykVSPackage.cs
Snyk.VisualStudio.Extension.2022/UI/Toolwindow/SnykToolWindowControl.xaml.cs
Snyk.VisualStudio.Extension.2022/packages.lock.json
Snyk.VisualStudio.Extension.Tests/Language/LsSettingsTest.cs
Snyk.VisualStudio.Extension.Tests/Language/SnykLanguageClientCustomTargetTests.cs
Snyk.VisualStudio.Extension.Tests/Language/SnykLanguageClientTest.cs
Snyk.VisualStudio.Extension.Tests/PackageBaseTest.cs
Snyk.VisualStudio.Extension.Tests/Service/FeatureFlagServiceTest.cs
Snyk.VisualStudio.Extension.Tests/TestUtils.cs

fix: languageClient tests

---

Snyk.VisualStudio.Extension.2022/UI/Html/BaseHtmlProvider.cs

Add css variable replacement for data-flow number

chore: add css variable for data-flow bubble

---

Snyk.VisualStudio.Extension.2022/packages.lock.json

chore: update packages.lock.json

---

Snyk.VisualStudio.Extension.2022/SnykVSPackage.cs

fix: after vs load init

---

.github/actions/next-git-tag/next-git-tag.ps1
.github/workflows/build-project.yml
.github/workflows/release-preview.yml
.github/workflows/release.yml
Snyk.VisualStudio.Extension.2022/Download/SnykCliDownloader.cs

* Support minor and major version bumps
* Set CLI default release channel to stable

chore: support minor major semver bumps

---

Snyk.VisualStudio.Extension.2022/Language/LsConstants.cs

chore: bump ls protocol version to 18

---

.github/workflows/resource-check.yml
Snyk.VisualStudio.Extension.2022/Resources/LoadingSummary.html

feat: compare sha512 hashes of static resoruces to reference files

---

.github/workflows/resource-check.yml
Snyk.VisualStudio.Extension.2022/Resources/LoadingSummary.html

feat: static resource checks

---

Snyk.VisualStudio.Extension.2022/UI/Tree/SnykFilterableTree.xaml.cs

fix: homogenize info nodes [IDE-936]

---

Snyk.VisualStudio.Extension.2022/Language/ILanguageClientManager.cs
Snyk.VisualStudio.Extension.2022/Language/LsConstants.cs
Snyk.VisualStudio.Extension.2022/Language/SnykLanguageClient.cs
Snyk.VisualStudio.Extension.2022/UI/Html/CodeHtmlProvider.cs
Snyk.VisualStudio.Extension.2022/UI/Toolwindow/HtmlDescriptionPanel.xaml.cs
Snyk.VisualStudio.Extension.2022/UI/Toolwindow/SnykScriptManager.cs

Handle the values from the JS provided by LS and call the `snyk.submitIgnoreRequest` LS command. Amended the CSS themes var replacements to be inline with the new LS CSS.
This PR also puts in a workaround to a bug with web views in Visual Studio not getting focus.
- No.
- No, the feature is going to be released as EA first.
- No, the feature is going to be released as EA first.

feat: handle IAW creation form [IDE-1075]

---

CHANGELOG.md

docs: update changelog for LS IVO filtering & IAW

---

CHANGELOG.md
Snyk.VisualStudio.Extension.2022/Language/LsConstants.cs

fix: bump ls protocol version

---

.github/workflows/readme-sync.yml

- N/A
- N/A
- N/A
- Automatically, hopefully.

chore: new README.md source path [IDE-1266]

---

.github/workflows/readme-sync.yml

chore(ci): correct docs sync path [IDA-563]
