snyk/snyk-visual-studio-plugin

- Snyk.Code.Library.Tests/SnykCode/SnykCodeClientTest.cs
- Snyk.Code.Library/Api/Dto/Analysis/AnalysisResultDto.cs
- Snyk.Code.Library/Domain/Analysis/AnalysisResult.cs
Fix deserialisation with json like
`"{\"status\":\"ANALYZING\",\"progress\":0.5,\"complete\":false}"`.
The issue was with progress type. It was long, but progress value could be 0.5.
> [ROAD-295] Fix: json deserialisation error

- Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/OssDescriptionControl.xaml
- Snyk.VisualStudio.Extension/Snyk/VisualStudio/Extension/UI/Toolwindow/OssDescriptionControl.xaml.cs
Moved Remediation information to top of the description panel in case of OSS results.
> [ROAD-344] Fix move remediation to top

- Snyk.Common/Sha256.cs
- Snyk.VisualStudio.Extension.2022/source.extension.vsixmanifest
- Snyk.VisualStudio.Extension.Shared/CLI/Download/ChecksumVerificationException.cs
- Snyk.VisualStudio.Extension.Shared/CLI/Download/LatestReleaseInfo.cs
- Snyk.VisualStudio.Extension.Shared/CLI/Download/SnykCliDownloader.cs
- Snyk.VisualStudio.Extension.Shared/Service/ISnykProgressWorker.cs
- Snyk.VisualStudio.Extension.Shared/Service/SnykProgressWorker.cs
- Snyk.VisualStudio.Extension.Shared/Service/SnykTasksService.cs
- Snyk.VisualStudio.Extension.Shared/Settings/SnykGeneralSettingsUserControl.cs
- Snyk.VisualStudio.Extension.Shared/Snyk.VisualStudio.Extension.Shared.projitems
- Snyk.VisualStudio.Extension.Tests/SnykCliDownloaderTest.cs
- Snyk.VisualStudio.Extension/source.extension.vsixmanifest
Fixed if cli file broken. After cli download finished it will verify file checksum and if it's wrong extension will try to download cli again.
> [ROAD-351] fix: check cli file checksum

- Snyk.Common/LogManager.cs
- Snyk.Common/Sentry/AbstractIntegration.cs
- Snyk.Common/Sentry/AppDomainAdapter.cs
- Snyk.Common/Sentry/AppDomainUnhandledExceptionIntegration.cs
- Snyk.Common/Sentry/IAppDomain.cs
- Snyk.Common/Sentry/TaskUnobservedTaskExceptionIntegration.cs
- Snyk.Common/Snyk.Common.csproj
- Snyk.VisualStudio.Extension.Shared/Service/SentryService.cs
To fix issue with not related to extension exceptions now it filter Sentry errors before send. It check Logger property and StackTrace content. 
Errors from extension must have SentryEvent.Logger = "Snyk.VisualStudio.CLI.SomeClass" property set. And also error must have Snyk mention in StackTrace
> [ROAD-682] fix: add check is sentry error related to extension

- Snyk.VisualStudio.Extension.2022/source.extension.vsixmanifest
When publishing 2022, it fails with the following message:
```
Error: 
(Snyk Vulnerability Scanner) Target 'Microsoft.VisualStudio.Community' with version range '[17.0,18.0)' specifies 'x86' as the target product architecture, but Visual Studio 2022 and above only supports `amd64`. More info at http://aka.ms/VS2022ExtensionSupport 
```
This PR addresses the problem.
> fix: Visual Studio 2022 supports amd64 only

- Snyk.VisualStudio.Extension.Shared/Service/SnykApiService.cs
- Snyk.VisualStudio.Extension.Tests/SnykApiServiceTest.cs
This PR adds a feature to check SAST API endpoint with organization from settings (if configured).
Organization will be added as URL query param:
```
<baseURL>/cli-config/settings/sast?org=<org-uuid-or-name>
```
> feat: sast settings with organization as url query param [ROAD-734]

- Snyk.Code.Library.Tests/SnykCode/CodeCacheServiceTest.cs
- Snyk.Code.Library.Tests/SnykCode/SnykCodeServiceTest.cs
- Snyk.Code.Library/Service/SnykCodeFileProvider.cs
- Snyk.Code.Library/Service/SnykCodeService.cs
- Snyk.Common/IFileProvider.cs
- Snyk.Common/ISolutionService.cs
- Snyk.VisualStudio.Extension.Shared/Service/SnykSolutionService.cs
- Snyk.VisualStudio.Extension.Shared/Service/SnykTasksService.cs
- Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/SnykToolWindowControl.xaml.cs
- Snyk.VisualStudio.Extension.Shared/UI/Tree/RootTreeNode.cs
- Snyk.VisualStudio.Extension.Shared/UI/Tree/RootTreeNodeState.cs
- Snyk.VisualStudio.Extension.Shared/UI/Tree/SnykFilterableTree.xaml.cs
In this PR reworked logic for get files in Solution. Now extension get solution files using VS toolkit api. 
First extension will check project/solution type. If project opened as folder it will get folder files using .net classes. If project is .net solution it will use VS toolkit api.
If project not contains files to scan it will show message in corresponding tree node item. For example
> [ROAD-659] Fix: sentry error parameter is incorrect

- Snyk.VisualStudio.Extension.Shared/Service/SnykApiService.cs
- Snyk.VisualStudio.Extension.Tests/SnykApiServiceTest.cs
Wrap sast response with try/catch in case of invalid json response from server. If server returned invalid json (for example, html text) it just return null value.
> [ROAD-660] fix: JsonReaderException unexpected character encountered while parsing

- Snyk.VisualStudio.Extension.2022/vs-publish.json
- Snyk.VisualStudio.Extension/vs-publish.json
Fixes https://github.com/snyk/snyk-visual-studio-plugin/runs/5968095874?check_suite_focus=true
>VSSDK: error VsixPub0006 : The publish manifest from 'D:\a\snyk-visual-studio-plugin\snyk-visual-studio-plugin\.\Snyk.VisualStudio.Extension\vs-publish.json' contains some invalid entries: Encountered an unsupported category: Tools..
As per https://stackoverflow.com/questions/57147010/is-it-possible-to-publish-a-visual-studio-template-extension-through-the-command question, default type for extension is "Tools" anyway, so no need to specify otherwise.
> fix: release categories

- .github/workflows/release.yml
- Snyk.VisualStudio.Extension.2022/source.extension.vsixmanifest
Fixes "VSSDK: error VsixPub0024 : The description for the extension must be set and it must be less than 280 characters in length." as reported in [the latest failed release](https://github.com/snyk/snyk-visual-studio-plugin/runs/5990477867?check_suite_focus=true).
> fix: vsix manifest length exceeding schema limit

- Snyk.VisualStudio.Extension.2022/vs-publish.json
- Snyk.VisualStudio.Extension/vs-publish.json
Fixes `VSSDK: error VsixPub0029 : An error occurred while communicating with the marketplace: The publisher name 'Snyk Ltd.' is invalid. Publisher names may only contain 'A' through 'Z', 'a' through 'z', '0' through '9' and '-'. The publisher name must start with an alphabetic or numeric character.`
> fix: publisher in release

- Snyk.VisualStudio.Extension.2022/source.extension.vsixmanifest
- Snyk.VisualStudio.Extension/source.extension.vsixmanifest
Attempt to fix `VSSDK: error VsixPub0029 : An error occurred while communicating with the marketplace: vsixId: The VSIX ID in the provided file is already in use. Every extension needs to have an unique ID. Provide a file with an unique ID.` in release.
> fix: vsix manifest publisher id

- Snyk.VisualStudio.Extension.2022/source.extension.vsixmanifest
- Snyk.VisualStudio.Extension/source.extension.vsixmanifest
Attempt to fix `VSSDK: error VsixPub0029 : An error occurred while communicating with the marketplace: vsixId: The VSIX ID in the provided file is already in use. Every extension needs to have an unique ID. Provide a file with an unique ID.`
- Use internal name from Marketplace as Identity Id in VSIX manifest. 
- Revert last PR with publisher name change
> fix: extension id for automated publishing

- Snyk.Code.Library.Tests/Snyk.Code.Library.Tests.csproj
- Snyk.Code.Library/Snyk.Code.Library.csproj
- Snyk.VisualStudio.Extension.2022/Snyk.VisualStudio.Extension.2022.csproj
- Snyk.VisualStudio.Extension.2022/source.extension.vsixmanifest
- Snyk.VisualStudio.Extension.2022/vs-publish.json
- Snyk.VisualStudio.Extension/source.extension.vsixmanifest
- Snyk.VisualStudio.Extension/vs-publish.json
- Bump up the SDK dependency versions.
- Revert [last extension id change](https://github.com/snyk/snyk-visual-studio-plugin/pull/131), change it in vs-publish.json instead.
- Upgrade Community Toolkit SDK to v17 that has correct VS 2022 support to avoid `The extension is incompatible with the targeted version of Visual Studio.` error when publishing VS 2022.
> fix: VsixCompatibility1001

- CHANGELOG.md
- Snyk.VisualStudio.Extension.2022/Snyk.VisualStudio.Extension.2022.csproj
- Snyk.VisualStudio.Extension.2022/source.extension.vsixmanifest
- Snyk.VisualStudio.Extension/source.extension.vsixmanifest
Fixes the following exception when launching extension in Visual Studio 2022. Most likely this occurs due to [the last change](https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/commit/972bef04aad23e1ba5cb30d0668bfba36d344500) in community toolkit.
> System.Windows.Markup.XamlParseException: Initialization of 'Snyk.VisualStudio.Extension.Shared.UI.Tree.SnykFilterableTree' threw an exception. ---> System.IO.IOException: Cannot locate resource 'themes/themeresources.xaml'.
at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
at System.IO.Packaging.PackagePart.GetStream(FileMode mode, FileAccess access)
at System.IO.Packaging.PackWebResponse.CachedResponse.GetResponseStream()
at System.IO.Packaging.PackWebResponse.get_ContentType()
at …
> fix: IOException in VS 2022

- CHANGELOG.md
- Snyk.VisualStudio.Extension.Shared/Service/SnykTasksService.cs
Before this changes extension first run OSS scan and only after this run Snyk Code scan. With this changes extension run a scan for OSS and for Snyk Code asynchronously.
> [ROAD-904] fix 🐛: run scan asynchronously

- CHANGELOG.md
- Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/SnykToolWindow.cs
- Snyk.VisualStudio.Extension.Shared/UI/Tree/SnykFilterableTree.xaml.cs
Fix issue with search/filter functionality. Now if user search or filter OSS/SnykCode results and after this clear search keyword it will restore all results in results tree.
> [ROAD-821] fix: restore all tree items after clear search

- .github/workflows/readme-sync.yml
Always use HEAD for image urls in readme sync to prevent bot detecting changes when it's only remote git head hash update.
> fix: always use HEAD for image urls in readme sync

- CHANGELOG.md
- Snyk.Code.Library.Tests/SnykCode/AnalysisServiceTest.cs
- Snyk.Code.Library/Service/AnalysisService.cs
…n in different places
This PR fix issue with not complete Snyk Code results. If one file has multiple identical suggestions it will show all of them.
> [ROAD-890] fix: lost some Snyk Code results in case one file with same suggestions

- CHANGELOG.md
- Snyk.VisualStudio.Extension.Shared/Service/SnykSolutionService.cs
If projects in solution organised via folders extension failed to get project path. Now this issue fixed. It check is dte project type is vsProjectKindSolutionFolder and in this case it will get project path using project sub projects items. 
Error on get all project paths from dte
> [ROAD-940] Fix error on get all project paths from dte

- CHANGELOG.md
- Snyk.VisualStudio.Extension.Shared/Snyk.VisualStudio.Extension.Shared.projitems
- Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/SnykCode/ExampleFixTab.cs
- Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/SnykCode/ExternalExampleFixRichTextBox.cs
- Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/SnykCode/ExternalExampleFixesControl.xaml
- Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/SnykCode/ExternalExampleFixesControl.xaml.cs
Right now external example fixes displayed in white theme even if user use dark VS theme. This PR fix this issue.
> [ROAD-305] fix: external example fixes dark theme support

- CHANGELOG.md
- Snyk.VisualStudio.Extension.Shared/Service/SnykSolutionService.cs
Fixed issue with Snyk Code results for WPF projects. This issue related to case when one physical file related to another (one parent and one child). For example
App.xaml
App.xaml.cs
> [ROAD-992] fix: snyk code results partially lost for wpf projects

- CHANGELOG.md
- Snyk.VisualStudio.Extension.Shared/Settings/SnykGeneralSettingsUserControl.Designer.cs
- Snyk.VisualStudio.Extension.Shared/Settings/SnykGeneralSettingsUserControl.cs
To provide good user experience we should explain what value does “organization” setting field should be filled with, similarly to what IntelliJ and Visual Studio is doing.
> [ROAD-873] feat: added organization info to settings (without tooltip)

- .github/workflows/readme-sync.yml
This fixes broken images when syncing readme from Gitbook.
Marketplace Markdown doesn't support special characters `<>` when adding a Markdown image. E.g. the following Markdown will not be printed correctly and instead interpreted as plaintext:
`![Visual Studio Code extension results](<https://github.com/snyk/user-docs/raw/HEAD/docs/.gitbook/assets/image (76) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1) (1).png>)`.
The fix is to replace these with <img> HTML tag using `sed` as part of readme sync.
> fix: broken images in readme sync

- Snyk.VisualStudio.Extension/source.extension.vsixmanifest
Updated the description of the LTS 2015-2019 version of VS to contain the date of the supported version.
This will affect the description on the VS Marketplace for this version and this version only.
> [ROAD-1023] fix:  Marketplace title correction for 2015-2019 VS

- CHANGELOG.md
- Snyk.VisualStudio.Extension.2022/Snyk.VisualStudio.Extension.2022.csproj
- Snyk.VisualStudio.Extension.Shared/Service/SnykTasksService.cs
A fix for compatibility problems with VS2022 versions smaller than 17.3.
Also fixes the stop button not working.
> fix: compatibility issues in VS2022 versions <17.3

- .github/workflows/build-project.yml
- .github/workflows/build.yml
- .github/workflows/integration-tests.yml
- .github/workflows/pr-workflow.yml
- .github/workflows/release.yml
- Snyk.VisualStudio.Extension.2022/Snyk.VisualStudio.Extension.2022.csproj
- Tests/Integration.Pre22.Tests/Integration.Pre22.Tests.csproj
- Tests/Integration.Tests/Integration.Tests.csproj
Fix the release workflow. Build on VS22 and run on VS19.
This change:
- Renames "build.yml" to "pr-workflow.yml"
- Added a "build-project.yml" reusable workflow
- Added a check that verifies that the secrets are accessible in the build step
- Added an "integration-tests.yml" reusable workflow
- Modified both the pr-workflow and the release workflow to use the reusable workflows
> fix: integration tests workflow [HEAD-294]

- Snyk.VisualStudio.Extension.2022/Snyk.VisualStudio.Extension.2022.csproj
- Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/DescriptionPanel.xaml.cs
- Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/OssDescriptionControl.xaml
- Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/OssDescriptionControl.xaml.cs
- Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/SnykToolWindowControl.xaml.cs
- Snyk.VisualStudio.Extension/Snyk.VisualStudio.Extension.csproj
Fixed markdown rendering of code blocks in the OSS description panel)
> [HEAD-331] fix: markdown rendering of code blocks in OSS description

- .snyk
_This PR adds several vulnerabilities caused by installed runtime versions to the ignore list. See Snyk guidance [here](https://docs.snyk.io/scan-applications/supported-languages-and-frameworks/.net#tackling-vulnerabilities-from-runtime-dependencies) on such vulnerabilities._
> chore: ignore runtime vulnerabilities that are not applicable

- Snyk.Common/Settings/ISnykOptions.cs
- Snyk.VisualStudio.Extension.Shared/CLI/SnykCli.cs
- Snyk.VisualStudio.Extension.Shared/CLI/SnykConsoleRunner.cs
- Snyk.VisualStudio.Extension.Shared/Service/SentryService.cs
- Snyk.VisualStudio.Extension.Shared/Service/SnykService.cs
- Snyk.VisualStudio.Extension.Shared/Settings/SnykGeneralOptionsDialogPage.cs
- Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/SnykToolWindowControl.xaml.cs
- Snyk.VisualStudio.Extension.Tests/SnykCliTest.cs
- Snyk.VisualStudio.Extension.Tests/SnykConsoleRunnerTest.cs
- Snyk.VisualStudio.Extension.Tests/SnykMockConsoleRunner.cs
> chore: disable analytics & sentry when fedramp [HEAD-677]

- CHANGELOG.md
- Snyk.Common/Settings/ISnykOptions.cs
- Snyk.VisualStudio.Extension.Shared/CLI/ICli.cs
- Snyk.VisualStudio.Extension.Shared/CLI/ICliProvider.cs
- Snyk.VisualStudio.Extension.Shared/CLI/SnykCli.cs
- Snyk.VisualStudio.Extension.Shared/Service/SnykService.cs
- Snyk.VisualStudio.Extension.Shared/Service/SnykTasksService.cs
- Snyk.VisualStudio.Extension.Shared/Settings/SnykGeneralOptionsDialogPage.cs
- Snyk.VisualStudio.Extension.Shared/Settings/SnykUserStorageSettingsService.cs
- Snyk.VisualStudio.Extension.Shared/Snyk.VisualStudio.Extension.Shared.projitems
- Snyk.VisualStudio.Extension.Shared/SnykVSPackage.cs
- Snyk.VisualStudio.Extension.Shared/analytics/ScanDoneEvent.cs
- Snyk.VisualStudio.Extension.Shared/analytics/SnykIdeAnalyticsService.cs
- Snyk.VisualStudio.Extension.Tests/SnykCliTest.cs
- Snyk.VisualStudio.Extension.Tests/analytics/SnykIDEAnalyticsServiceTest.cs
> feat: send analytics after scans by calling the CLI

- CHANGELOG.md
- Snyk.Common/Settings/ISnykOptions.cs
- Snyk.VisualStudio.Extension.Shared/CLI/SnykConsoleRunner.cs
- Snyk.VisualStudio.Extension.Shared/Service/SnykService.cs
- Snyk.VisualStudio.Extension.Shared/Settings/SnykGeneralOptionsDialogPage.cs
- Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/SnykToolWindowControl.xaml.cs
- Snyk.VisualStudio.Extension.Tests/GeneralOptionsDialogPage.cs
- Snyk.VisualStudio.Extension.Tests/SnykCliTest.cs
- Snyk.VisualStudio.Extension.Tests/SnykConsoleRunnerTest.cs
Disables sending analytics events to Amplitude when connected to a non-US MT or FedRAMP environment.
Co-authored-by: Knut <knut.funkel@snyk.io>
https://snyksec.atlassian.net/browse/IDE-24
> Only send Amplitude analytics events when connected to an MT US environment

- CHANGELOG.md
- Snyk.Code.Library/Snyk.Code.Library.csproj
- Snyk.Common/Snyk.Common.csproj
This patch Upgrade the version of the Newtonsoft dependency.
> fix: upgrading package version on Newtonsoft IDE-218

- CHANGELOG.md
- Snyk.VisualStudio.Extension.Shared/Service/SnykCodeScanEventArgs.cs
- Snyk.VisualStudio.Extension.Shared/Service/SnykTasksService.cs
- Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/SnykToolWindowControl.xaml.cs
- Send User settings when Code or Quality Scanning Events are triggered to ensure correctly setting the TreeNode state.
- If a scan type is disabled, clear the TreeNode. 
> fix: [IDE-219] send settings when firing scan events

- .github/workflows/readme-sync.yml
Fix failing readme-sync pipeline. 
It appears that the folder structure of snyk/user-docs has changed. 
This change update the SOURCE_PATH variable to use the correct README.md file.
> fix: readme-sync pipeline [IDE-343]

- CHANGELOG.md
- Snyk.VisualStudio.Extension.Shared/Snyk.VisualStudio.Extension.Shared.projitems
- Snyk.VisualStudio.Extension.Shared/Theme/ColorExtension.cs
- Snyk.VisualStudio.Extension.Shared/UI/Toolwindow/SnykCode/ExternalExampleFixRichTextBox.cs
Replace background color for fixes lines in the ``ExternalExampleFixRichTextBox`` with IDE colors instead of static colors.
For Green:
``EnvironmentColors.VizSurfaceGreenDarkBrushKey``
For Red:
``EnvironmentColors.VizSurfaceRedDarkBrushKey``
For Reference:
All VS Colors: https://vscolor.sboulema.nl
Before for all themes: 
After:
> fix: use VS Brushes for background color

- CHANGELOG.md
- Snyk.VisualStudio.Extension.Shared/Service/SnykService.cs
- Snyk.VisualStudio.Extension.Shared/analytics/ScanDoneEvent.cs
- Snyk.VisualStudio.Extension.Shared/analytics/SnykIdeAnalyticsService.cs
- Snyk.VisualStudio.Extension.Tests/analytics/SnykIDEAnalyticsServiceTest.cs
- Before sending analytics get the current folder/solution path and assign it to the ScanDoneEvent attributes.
Note: This change was tested with older CLI versions. 
The additional property "path" is ignored in older CLI version.
> chore: add folder path to analytics event

- CHANGELOG.md
- Snyk.Common/Snyk.Common.csproj
- Snyk.VisualStudio.Extension.2022/Snyk.VisualStudio.Extension.2022.csproj
- Snyk.VisualStudio.Extension.Shared/Settings/SnykGeneralSettingsUserControl.cs
- Snyk.VisualStudio.Extension/Properties/AssemblyInfo.cs
- Snyk.VisualStudio.Extension/Snyk.VisualStudio.Extension.csproj
VS 2022 Version < 17.9 don't have the required binding redirect for System.Diagnostics.DiagnosticSource. 
System.Diagnostics.DiagnosticSource is required by Serilog > 3.0.1.
For now, we can just downgrade to 3.0.1.
Fix a small bug with enable Snyk code label
> fix: downgrade serilog to 3.0.1 and remove bindingredirect

- .github/actions/next-git-tag/patch-manifest.ps1
- .github/workflows/build-project.yml
- .github/workflows/release-preview.yml
> chore: update GH actions

- .github/workflows/release.yml
- CHANGELOG.md
- Snyk.VisualStudio.Extension.2022/Commands/SnykScanCommand.cs
- Snyk.VisualStudio.Extension.2022/Extension/UriExtensions.cs
- Snyk.VisualStudio.Extension.2022/Language/LsSettings.cs
- Snyk.VisualStudio.Extension.2022/Language/SnykLanguageClient.cs
- Snyk.VisualStudio.Extension.2022/Language/SnykLanguageClientCustomTarget.cs
- Snyk.VisualStudio.Extension.2022/Language/SnykLanguageClientMiddleware.cs
- Snyk.VisualStudio.Extension.2022/LogManager.cs
- Snyk.VisualStudio.Extension.2022/Service/ISolutionService.cs
- Snyk.VisualStudio.Extension.2022/Service/SnykSolutionService.cs
- Snyk.VisualStudio.Extension.2022/Service/SnykTasksService.cs
- Snyk.VisualStudio.Extension.2022/Service/SnykVsSolutionLoadEvents.cs
- Snyk.VisualStudio.Extension.2022/Service/WorkspaceTrustService.cs
- Snyk.VisualStudio.Extension.2022/Settings/ISnykOptionsManager.cs
- Snyk.VisualStudio.Extension.2022/Settings/SnykCliOptionsUserControl.Designer.cs
- Snyk.VisualStudio.Extension.2022/Settings/SnykCliOptionsUserControl.cs
- Snyk.VisualStudio.Extension.2022/Settings/SnykGeneralOptionsDialogPage.cs
- Snyk.VisualStudio.Extension.2022/Settings/SnykOptionsManager.cs
- Snyk.VisualStudio.Extension.2022/Settings/SnykSolutionOptionsUserControl.cs
- Snyk.VisualStudio.Extension.2022/SnykVSPackage.cs
- Snyk.VisualStudio.Extension.2022/UI/Toolwindow/MessagePanel.xaml.cs
- Snyk.VisualStudio.Extension.2022/UI/Toolwindow/SnykToolWindowControl.xaml.cs
- Snyk.VisualStudio.Extension.2022/UI/Tree/SnykFilterableTree.xaml.cs
- Snyk.VisualStudio.Extension.Tests/Language/LsSettingsTest.cs
- Snyk.VisualStudio.Extension.Tests/Language/SnykLanguageClientCustomTargetTests.cs
- Snyk.VisualStudio.Extension.Tests/SnykCliDownloaderTest.cs
* URI to Path conversion should handle non-ascii characters.
* Added ThreadContextEnricher to Logger.
* Fixed Additional Options persistence.
* Disable LS Trust and rely only on extension trust logic.
* Ensure Scan and Trust commands are running in the Background.
> fix: non-ascii characters in path

- CHANGELOG.md
- Snyk.VisualStudio.Extension.2022/Language/CustomInitializationOptions.cs
- Snyk.VisualStudio.Extension.2022/Language/LsConstants.cs
- Snyk.VisualStudio.Extension.2022/Language/SnykLanguageClientCustomTarget.cs
- Snyk.VisualStudio.Extension.2022/Resources/LoadingSummary.html
- Snyk.VisualStudio.Extension.2022/Snyk.VisualStudio.Extension.2022.csproj
- Snyk.VisualStudio.Extension.2022/Theme/ColorExtension.cs
- Snyk.VisualStudio.Extension.2022/UI/Html/BaseHtmlProvider.cs
- Snyk.VisualStudio.Extension.2022/UI/Html/ColorExtension.cs
- Snyk.VisualStudio.Extension.2022/UI/Html/HtmlProviderFactory.cs
- Snyk.VisualStudio.Extension.2022/UI/Html/StaticHtmlProvider.cs
- Snyk.VisualStudio.Extension.2022/UI/Html/SummaryHtmlProvider.cs
- Snyk.VisualStudio.Extension.2022/UI/Toolwindow/SnykScriptManager.cs
- Snyk.VisualStudio.Extension.2022/UI/Toolwindow/SnykToolWindowControl.xaml
- Snyk.VisualStudio.Extension.2022/UI/Toolwindow/SnykToolWindowControl.xaml.cs
- Snyk.VisualStudio.Extension.2022/UI/Toolwindow/SummaryHtmlPanel.xaml
- Snyk.VisualStudio.Extension.2022/UI/Toolwindow/SummaryHtmlPanel.xaml.cs
This PR introduces the HTML Summary Panel which we get through the `$/snyk.scanSummary` notification and handle toggling Delta Findings option on/off trough the HTML toggle element.
- Create `ToolWindow` for the Summary Panel
- Handle `$/snyk.scanSummary` notification and update the content of the SummaryPanel ToolWindow with the recieved HTML
- Add additional IDE-specific styling and add needed CSS variables
- Handle toggling the Delta Setting by sending a `didChangeConfiguration` when toggling between the **New** and **All Issues** in the summary panel. 
> feat: handle summary panel notification and render it in toolwindow [IDE-893]

- Snyk.VisualStudio.Extension.2022/BranchSelectorDialogWindow.xaml
- Snyk.VisualStudio.Extension.2022/BranchSelectorDialogWindow.xaml.cs
- Snyk.VisualStudio.Extension.2022/Language/CustomInitializationOptions.cs
- Snyk.VisualStudio.Extension.2022/UI/Toolwindow/SnykScriptManager.cs
Added Reference Folder option for Delta scan
> feat: reference folder for delta scan [IDE-953]

- CHANGELOG.md
- Snyk.VisualStudio.Extension.2022/UI/Tree/SnykFilterableTree.xaml.cs
Previously the total issue counts for "Code Security" and "Code Quality" were being combined in the tree navigation.
> fix: total issue counts for code scans [IDE-944]

- CHANGELOG.md
- Snyk.VisualStudio.Extension.2022/Language/ILanguageClientManager.cs
- Snyk.VisualStudio.Extension.2022/Language/LsAnalysisResult.cs
- Snyk.VisualStudio.Extension.2022/Language/LsConstants.cs
- Snyk.VisualStudio.Extension.2022/Language/SnykLanguageClient.cs
- Snyk.VisualStudio.Extension.2022/Language/SnykLanguageClientCustomTarget.cs
- Snyk.VisualStudio.Extension.2022/UI/Html/BaseHtmlProvider.cs
- Snyk.VisualStudio.Extension.2022/UI/Html/CodeHtmlProvider.cs
- Snyk.VisualStudio.Extension.2022/UI/Toolwindow/SnykScriptManager.cs
- Snyk.VisualStudio.Extension.2022/UI/Toolwindow/SnykToolWindowControl.xaml.cs
- Snyk.VisualStudio.Extension.2022/UI/Tree/SnykFilterableTree.xaml
- Snyk.VisualStudio.Extension.2022/UI/Tree/SnykFilterableTree.xaml.cs
* Handle window/showDocument with snyk scheme
* Select issue from snyk URI in the Tree and ensure that the HTML is rendered.
* generate code.fixDiffs command
* applyFixDiffs command
> feat: Apply Edit and ShowDocument command [IDE-958]

- CHANGELOG.md
- Snyk.VisualStudio.Extension.2022/UI/Tree/OssFileTreeNode.cs
In a multi-project setup OSS issue tree node was showing "rootFolder/project.assets.json"
Making it very hard to distinguish in which this specific OSS issue was found.
This fix will instead calculate a relative path from currentFolder and the absolute filePath where the OSS issue was found.
> fix: title for OSS issue tree node

- Snyk.VisualStudio.Extension.2022/Settings/SnykGeneralSettingsUserControl.Designer.cs
- Snyk.VisualStudio.Extension.2022/Settings/SnykGeneralSettingsUserControl.cs
- Snyk.VisualStudio.Extension.2022/Settings/SnykGeneralSettingsUserControl.resx
In IDEs, you can configure a custom endpoint in order to target a custom region (e.g EU). The current description for this option is "Sets API endpoint to use for Snyk requests. Useful for custom Snyk setups. E.g. https://api.eu.snyk.io/.". With the recent platform changes, on OAuth using SSO, we automatically redirect to the right instance and that field does not need to be configured anymore.
> fix: update custom endpoint description [IDE-1081]
